name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: 'arun-cloud-resume'   # Your function app name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'           # Path to your function app project
  PYTHON_VERSION: '3.11'                        # Python version to use
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Azure Subscription ID
  AZURE_RESOURCE_GROUP: 'YourResourceGroupName' # Azure Resource Group name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: Run tests
      run: |
        pip install -r requirements.txt
        pytest function_app_tests.py

    - name: Deploy ARM template
      if: success()
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: path/to/your/arm_template.json
        parameters: path/to/your/arm_template_parameters.json

    - name: Deploy to Azure Function App
      if: success()
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
